"""Build the fixed Create TFRecords notebook."""
import json

def md(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source if isinstance(source, list) else [source]}

def code(source):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": source if isinstance(source, list) else [source]}

cells = []

# ── TITLE ─────────────────────────────────────────────────────────────────────
cells.append(md([
    "# Create TFRecords — cGAN Retraining with RFE2 Daily Data\n",
    "\n",
    "**Purpose:** Converts RFE2 daily rainfall + IFS forecast data into TFRecord files for cGAN training.\n",
    "\n",
    "**Run environment:** Google Colab (GPU runtime recommended)\n",
    "\n",
    "---\n",
    "### Key Design Decision\n",
    "- Original IMERG model: **6-hourly**. RFE2: **daily (mm/day)**.\n",
    "- This notebook uses the **daily approach**: one training sample per day,\n",
    "  IFS forecast at lead time 30h, truth = full daily RFE2 (log-normalised).\n",
    "- RFE2 is **NOT divided by 4** — that assumes uniform rainfall distribution which is physically wrong.\n",
    "\n",
    "---\n",
    "### Run order — do not skip cells\n",
    "| Cell | What it does |\n",
    "|---|---|\n",
    "| 1 | Mount Drive, set paths |\n",
    "| 2 | Inspect Drive zips, unzip RFE2 |\n",
    "| 3 | Clone repo, install packages |\n",
    "| 4 | Set variables |\n",
    "| 5 | Download IFS + constants from GCS |\n",
    "| 6 | Fix FCSTNorm (copy correct IFS version) |\n",
    "| 7 | Write config files |\n",
    "| 8 | **PATCH CELL** — must re-run every session |\n",
    "| 9 | Diagnostics — all checks must pass |\n",
    "| 10 | Verify sample + plot |\n",
    "| 11 | Create TFRecords |\n",
    "| 12 | Summary |"
]))

# ── CELL 1: Mount + Paths ─────────────────────────────────────────────────────
cells.append(md("## Cell 1 — Mount Drive and Set Paths"))
cells.append(code([
    "from google.colab import drive\n",
    "import os\n",
    "\n",
    "drive.mount('/content/drive')\n",
    "\n",
    "# ── Google Drive paths (persistent) ────────────────────────────────────────\n",
    "RFE_ZIPS_DIR = '/content/drive/MyDrive/RFE_zips'        # yearly zip files\n",
    "OUTPUT_DIR   = '/content/drive/MyDrive/rfe_tfrecords'   # TFRecords output\n",
    "\n",
    "# ── Local Colab disk paths (fast, wiped on session end) ────────────────────\n",
    "RFE_DATA_DIR  = '/content/rfe_data'     # unzipped RFE2 files\n",
    "CONSTANTS_DIR = '/content/constants/'   # elev.nc, lsm.nc, FCSTNorm\n",
    "RAW_IFS_DIR   = '/content/raw_ifs/'     # downloaded IFS forecast files\n",
    "\n",
    "for d in [RFE_DATA_DIR, CONSTANTS_DIR, RAW_IFS_DIR, OUTPUT_DIR]:\n",
    "    os.makedirs(d, exist_ok=True)\n",
    "\n",
    "print('Drive mounted.')\n",
    "print(f'  RFE zips  : {RFE_ZIPS_DIR}')\n",
    "print(f'  Output    : {OUTPUT_DIR}')\n",
    "print(f'  RFE data  : {RFE_DATA_DIR}')\n",
    "print(f'  Constants : {CONSTANTS_DIR}')\n",
    "print(f'  IFS dir   : {RAW_IFS_DIR}')"
]))

# ── CELL 2: Inspect + Unzip ───────────────────────────────────────────────────
cells.append(md([
    "## Cell 2 — Inspect Drive Zips and Unzip RFE2 Data\n",
    "\n",
    "This cell first shows what zips are available in your Drive folder,\n",
    "then unzips each one to the fast local disk.\n",
    "\n",
    "**If a zip is missing from Drive:** Upload it from your local `E:\\CGAN\\RFE_zips\\` folder\n",
    "before continuing.\n",
    "\n",
    "**The cell handles two common zip structures automatically:**\n",
    "- `year/YYYYMMDD.nc` (files nested inside year folder) — standard\n",
    "- `YYYYMMDD.nc` (files at root of zip) — also handled"
]))
cells.append(code([
    "import zipfile, os\n",
    "\n",
    "TRAIN_YEARS = list(range(2001, 2021))   # 2001-2020 for training\n",
    "VAL_YEARS   = [2021, 2022]              # held-out for validation\n",
    "ALL_YEARS   = TRAIN_YEARS + VAL_YEARS\n",
    "\n",
    "# ── Step 1: Inspect what zips are available in Drive ───────────────────────\n",
    "print('Checking Drive zip folder:', RFE_ZIPS_DIR)\n",
    "if not os.path.exists(RFE_ZIPS_DIR):\n",
    "    print('  ERROR: RFE_ZIPS_DIR not found.')\n",
    "    print('  Create the folder MyDrive/RFE_zips/ and upload your year zips.')\n",
    "else:\n",
    "    available_zips = sorted(os.listdir(RFE_ZIPS_DIR))\n",
    "    print(f'  Found {len(available_zips)} files in Drive:')\n",
    "    for z in available_zips:\n",
    "        size_mb = os.path.getsize(os.path.join(RFE_ZIPS_DIR, z)) / 1e6\n",
    "        print(f'    {z}  ({size_mb:.0f} MB)')\n",
    "\n",
    "    zip_years = [z.replace('.zip','') for z in available_zips if z.endswith('.zip')]\n",
    "    missing_zips = [str(y) for y in ALL_YEARS if str(y) not in zip_years]\n",
    "    if missing_zips:\n",
    "        print(f'\\n  Missing zips for years: {missing_zips}')\n",
    "        print('  Upload the missing zips to Drive before running TFRecord creation.')\n",
    "    else:\n",
    "        print('  All required zips found.')\n",
    "\n",
    "print()\n",
    "\n",
    "# ── Step 2: Unzip each year ─────────────────────────────────────────────────\n",
    "def smart_unzip(zip_path, year, dest_base):\n",
    "    \"\"\"\n",
    "    Unzip RFE2 year zip to dest_base/year/YYYYMMDD.nc\n",
    "    regardless of zip structure:\n",
    "      - YYYYMMDD.nc (flat)\n",
    "      - year/YYYYMMDD.nc (subdir, forward slash)\n",
    "      - year\\\\YYYYMMDD.nc (Windows backslash from Compress-Archive)\n",
    "    Reads each entry directly so path separator issues are irrelevant.\n",
    "    \"\"\"\n",
    "    year_dir = os.path.join(dest_base, str(year))\n",
    "    os.makedirs(year_dir, exist_ok=True)\n",
    "    with zipfile.ZipFile(zip_path, 'r') as z:\n",
    "        names = z.namelist()\n",
    "        # Show first 3 entries so user can see zip structure\n",
    "        print(f'    [{len(names)} entries | first 3: {names[:3]}]', end=' ', flush=True)\n",
    "        for member in z.infolist():\n",
    "            # Normalize separators: Windows \\ and forward /\n",
    "            norm = member.filename.replace('\\\\', '/').replace('//', '/')\n",
    "            # Get just the base filename (strip any leading year/ or other dirs)\n",
    "            basename = norm.split('/')[-1]\n",
    "            if not basename.endswith('.nc'):\n",
    "                continue  # skip directories and non-nc files\n",
    "            dest_file = os.path.join(year_dir, basename)\n",
    "            if os.path.exists(dest_file):\n",
    "                continue\n",
    "            # Read raw bytes and write — avoids all path separator issues\n",
    "            data = z.read(member.filename)\n",
    "            with open(dest_file, 'wb') as f:\n",
    "                f.write(data)\n",
    "\n",
    "for year in ALL_YEARS:\n",
    "    dest     = os.path.join(RFE_DATA_DIR, str(year))\n",
    "    zip_path = os.path.join(RFE_ZIPS_DIR, f'{year}.zip')\n",
    "\n",
    "    if os.path.exists(dest) and len(os.listdir(dest)) > 300:\n",
    "        print(f'  {year} already unzipped ({len(os.listdir(dest))} files). Skipping.')\n",
    "        continue\n",
    "\n",
    "    if not os.path.exists(zip_path):\n",
    "        print(f'  {year} — zip not found in Drive. Skipping.')\n",
    "        continue\n",
    "\n",
    "    print(f'  {year} — unzipping...', end=' ', flush=True)\n",
    "    smart_unzip(zip_path, year, RFE_DATA_DIR)\n",
    "\n",
    "    # Verify extraction landed in the right place\n",
    "    if os.path.exists(dest):\n",
    "        count = len(os.listdir(dest))\n",
    "        print(f'done ({count} files at {dest})')\n",
    "    else:\n",
    "        # Try to find where files landed\n",
    "        found = [d for d in os.listdir(RFE_DATA_DIR)\n",
    "                 if os.path.isdir(os.path.join(RFE_DATA_DIR, d))]\n",
    "        print(f'WARN: expected {dest} but found dirs: {found}')\n",
    "\n",
    "print()\n",
    "print('RFE2 data directory after unzip:')\n",
    "try:\n",
    "    dirs = sorted(os.listdir(RFE_DATA_DIR))\n",
    "    for d in dirs:\n",
    "        full = os.path.join(RFE_DATA_DIR, d)\n",
    "        if os.path.isdir(full):\n",
    "            n = len(os.listdir(full))\n",
    "            print(f'  {d}/  ({n} files)')\n",
    "        else:\n",
    "            print(f'  {d}  (file — unexpected at root level)')\n",
    "except Exception as e:\n",
    "    print('Error listing dir:', e)"
]))

# ── CELL 3: Clone + Install ───────────────────────────────────────────────────
cells.append(md([
    "## Cell 3 — Clone Repo and Install Packages\n",
    "\n",
    "- `%cd /content/cGAN_tutorial` changes the working directory permanently for this session\n",
    "- `scipy` is required for `RegularGridInterpolator` (regrids RFE2 onto IFS grid)\n",
    "- The `if` guard means safe to re-run on restart"
]))
cells.append(code([
    "import os\n",
    "\n",
    "if not os.path.exists('/content/cGAN_tutorial'):\n",
    "    !git clone https://github.com/snath-xoc/cGAN_tutorial.git /content/cGAN_tutorial\n",
    "    print('Cloned cGAN_tutorial.')\n",
    "else:\n",
    "    print('Repo already exists.')\n",
    "\n",
    "%cd /content/cGAN_tutorial\n",
    "print('Working directory:', os.getcwd())\n",
    "\n",
    "!pip install -q xarray netCDF4 gcsfs joblib pyyaml tensorflow cartopy scipy properscoring\n",
    "print('All packages ready.')"
]))

# ── CELL 4: Variables ─────────────────────────────────────────────────────────
cells.append(md([
    "## Cell 4 — Set Forecast Variables\n",
    "\n",
    "| Variable | Full name | Role |\n",
    "|---|---|---|\n",
    "| `tp` | Total precipitation | Primary rainfall signal |\n",
    "| `t2m` | 2m temperature | Warm/cold air mass indicator |\n",
    "| `tcwv` | Total column water vapour | Atmospheric moisture fuel |\n",
    "| `sp` | Surface pressure | Synoptic flow pattern |\n",
    "\n",
    "`YEAR = 2018` — IFS data on GCS is only available for 2018.\n",
    "RFE2 truth data comes from your own uploaded zips (any year)."
]))
cells.append(code([
    "import sys\n",
    "sys.path.insert(0, '/content/cGAN_tutorial')\n",
    "\n",
    "FORECAST_VARIABLES = ['tp', 't2m', 'tcwv', 'sp']\n",
    "YEAR       = 2018    # IFS year on GCS\n",
    "START_HOUR = 30      # Lead time: 30h (one slot per day)\n",
    "END_HOUR   = 54\n",
    "\n",
    "print(f'Forecast variables : {FORECAST_VARIABLES}')\n",
    "print(f'Input channels     : {4 * len(FORECAST_VARIABLES)}  (4 vars x 4 stats each)')\n",
    "print(f'IFS year           : {YEAR}')\n",
    "print(f'Lead time window   : {START_HOUR}h to {END_HOUR}h')"
]))

# ── CELL 5: Download IFS + constants ─────────────────────────────────────────
cells.append(md([
    "## Cell 5 — Download IFS Forecast Data and Constants from GCS\n",
    "\n",
    "**Step 1:** Authenticates your Google account so `gsutil` can access the private `sewaa-ifs-train` bucket.\n",
    "A browser popup will appear — sign in with the account that has access to the SEWAA bucket.\n",
    "\n",
    "**Step 2:** Downloads four things:\n",
    "1. IFS forecast variables: `tp.nc`, `t2m.nc`, `tcwv.nc`, `sp.nc` (~500 MB each)\n",
    "2. Elevation: `elev.nc`\n",
    "3. Land-sea mask: `lsm.nc`\n",
    "4. FCSTNorm (IFS version — correct one, copied into place by Cell 6)\n",
    "\n",
    "> **Note:** The GEFS `FCSTNorm2018.pkl` sits at `constants/` root — **do not use it**.\n",
    "> The IFS one lives at `constants/FCSTNorm_IFS/` — Cell 6 copies it to the right location."
]))
cells.append(code([
    "import os\n",
    "\n",
    "# ── Step 1: Authenticate with Google (required for private GCS bucket) ──────\n",
    "from google.colab import auth\n",
    "auth.authenticate_user()\n",
    "print('Google authentication complete.')\n",
    "\n",
    "IFS_YEAR_DIR = os.path.join(RAW_IFS_DIR, str(YEAR))\n",
    "os.makedirs(IFS_YEAR_DIR, exist_ok=True)\n",
    "\n",
    "def gsutil_download(src, dest_dir, filename=None):\n",
    "    \"\"\"Download from GCS and verify the file arrived.\"\"\"\n",
    "    dest_file = os.path.join(dest_dir, filename or os.path.basename(src))\n",
    "    if os.path.exists(dest_file) and os.path.getsize(dest_file) > 1000:\n",
    "        print(f'  {os.path.basename(dest_file)} already exists ({os.path.getsize(dest_file)/1e6:.1f} MB). Skipping.')\n",
    "        return True\n",
    "    print(f'  Downloading {os.path.basename(src)} ...', end=' ', flush=True)\n",
    "    ret = os.system(f'gsutil -m cp {src} {dest_dir}/')\n",
    "    if os.path.exists(dest_file) and os.path.getsize(dest_file) > 1000:\n",
    "        print(f'OK ({os.path.getsize(dest_file)/1e6:.1f} MB)')\n",
    "        return True\n",
    "    else:\n",
    "        print(f'FAILED  (exit code {ret})')\n",
    "        return False\n",
    "\n",
    "all_ok = True\n",
    "\n",
    "# 1. IFS forecast variables\n",
    "print('--- IFS forecast variables ---')\n",
    "for var in FORECAST_VARIABLES:\n",
    "    ok = gsutil_download(f'gs://sewaa-ifs-train/{YEAR}/{var}.nc', IFS_YEAR_DIR)\n",
    "    all_ok = all_ok and ok\n",
    "\n",
    "# 2. Static constants\n",
    "print('\\n--- Static constants ---')\n",
    "for fname in ['elev.nc', 'lsm.nc']:\n",
    "    ok = gsutil_download(f'gs://sewaa-ifs-train/constants/{fname}', CONSTANTS_DIR)\n",
    "    all_ok = all_ok and ok\n",
    "\n",
    "# 3. FCSTNorm IFS (correct one)\n",
    "print('\\n--- FCSTNorm (IFS version — CORRECT) ---')\n",
    "ifs_norm_dir = os.path.join(CONSTANTS_DIR, 'FCSTNorm_IFS')\n",
    "os.makedirs(ifs_norm_dir, exist_ok=True)\n",
    "ok = gsutil_download(\n",
    "    f'gs://sewaa-ifs-train/constants/FCSTNorm_IFS/FCSTNorm{YEAR}.pkl',\n",
    "    ifs_norm_dir)\n",
    "all_ok = all_ok and ok\n",
    "\n",
    "# 4. FCSTNorm GEFS (wrong one — saved separately for reference only)\n",
    "print('\\n--- FCSTNorm (GEFS version — DO NOT USE for training) ---')\n",
    "gsutil_download(\n",
    "    f'gs://sewaa-ifs-train/constants/FCSTNorm{YEAR}.pkl',\n",
    "    CONSTANTS_DIR, filename=f'FCSTNorm{YEAR}_GEFS.pkl')\n",
    "\n",
    "print()\n",
    "print('Download summary:')\n",
    "print(f'  IFS_YEAR_DIR : {IFS_YEAR_DIR}')\n",
    "for f in sorted(os.listdir(IFS_YEAR_DIR)):\n",
    "    sz = os.path.getsize(os.path.join(IFS_YEAR_DIR, f)) / 1e6\n",
    "    print(f'    {f}  ({sz:.0f} MB)')\n",
    "print(f'  CONSTANTS_DIR: {CONSTANTS_DIR}')\n",
    "for f in sorted(os.listdir(CONSTANTS_DIR)):\n",
    "    full = os.path.join(CONSTANTS_DIR, f)\n",
    "    if os.path.isfile(full):\n",
    "        sz = os.path.getsize(full) / 1e6\n",
    "        print(f'    {f}  ({sz:.1f} MB)')\n",
    "    else:\n",
    "        print(f'    {f}/  (directory)')\n",
    "\n",
    "if not all_ok:\n",
    "    print('\\nWARNING: Some downloads failed. Check your internet connection or GCS bucket access.')\n",
    "else:\n",
    "    print('\\nAll downloads verified.')"
]))

# ── CELL 6: FCSTNorm fix ──────────────────────────────────────────────────────
cells.append(md([
    "## Cell 6 — Fix FCSTNorm: Copy the Correct IFS File\n",
    "\n",
    "The `data.py` module looks for `FCSTNorm{YEAR}.pkl` directly in `CONSTANTS_PATH`.\n",
    "We must ensure it finds the **IFS** version, not the GEFS one.\n",
    "\n",
    "| File | What it is | Use |\n",
    "|---|---|---|\n",
    "| `constants/FCSTNorm2018.pkl` | GEFS normalization | **WRONG** — do not use for IFS training |\n",
    "| `constants/FCSTNorm_IFS/FCSTNorm2018.pkl` | IFS normalization | **CORRECT** — copy this one |"
]))
cells.append(code([
    "import shutil, joblib, os\n",
    "\n",
    "correct_src = os.path.join(CONSTANTS_DIR, 'FCSTNorm_IFS', f'FCSTNorm{YEAR}.pkl')\n",
    "final_dest  = os.path.join(CONSTANTS_DIR, f'FCSTNorm{YEAR}.pkl')\n",
    "\n",
    "if not os.path.exists(correct_src):\n",
    "    raise FileNotFoundError(\n",
    "        f'IFS FCSTNorm not found at: {correct_src}\\n'\n",
    "        f'Re-run Cell 5 to download it.')\n",
    "\n",
    "shutil.copy(correct_src, final_dest)\n",
    "print(f'Copied: {correct_src}')\n",
    "print(f'    to: {final_dest}')\n",
    "\n",
    "# Verify it loads and has expected content\n",
    "norm = joblib.load(final_dest)\n",
    "if isinstance(norm, dict):\n",
    "    print(f'\\nLoaded FCSTNorm: {len(norm)} variables')\n",
    "    print(f'Variables: {list(norm.keys())}')\n",
    "    if 'tp' in norm:\n",
    "        print('tp normalization looks correct.')\n",
    "    else:\n",
    "        print('WARNING: tp not in norm dict. Check this is really the IFS norm file.')\n",
    "else:\n",
    "    print(f'Loaded FCSTNorm type: {type(norm)}')\n",
    "print('\\nFCSTNorm fix complete.')"
]))

# ── CELL 7: Config ────────────────────────────────────────────────────────────
cells.append(md([
    "## Cell 7 — Write Config Files\n",
    "\n",
    "Writes `data_paths.yaml` and `local_config.yaml` into the cGAN repo's config folder.\n",
    "The key change: `TRUTH_PATH` points to your RFE2 data directory instead of IMERG."
]))
cells.append(code([
    "import yaml\n",
    "\n",
    "data_paths = {\n",
    "    'COLAB_RFE2': {\n",
    "        'GENERAL': {\n",
    "            'FORECAST_PATH':      RAW_IFS_DIR,\n",
    "            'TRUTH_PATH':         RFE_DATA_DIR + '/',\n",
    "            'CONSTANTS_PATH':     CONSTANTS_DIR,\n",
    "            'NORMALISATION_PATH': CONSTANTS_DIR,\n",
    "        },\n",
    "        'TFRecords': {\n",
    "            'tfrecords_path': OUTPUT_DIR + '/'\n",
    "        }\n",
    "    }\n",
    "}\n",
    "\n",
    "with open('config/data_paths.yaml', 'w') as f:\n",
    "    yaml.dump(data_paths, f, default_flow_style=False)\n",
    "\n",
    "with open('config/local_config.yaml', 'w') as f:\n",
    "    yaml.dump({'data_paths': 'COLAB_RFE2', 'gpu': False}, f)\n",
    "\n",
    "print('Config files written.')\n",
    "print()\n",
    "print('TRUTH_PATH    :', data_paths['COLAB_RFE2']['GENERAL']['TRUTH_PATH'])\n",
    "print('FORECAST_PATH :', data_paths['COLAB_RFE2']['GENERAL']['FORECAST_PATH'])\n",
    "print('tfrecords_path:', data_paths['COLAB_RFE2']['TFRecords']['tfrecords_path'])"
]))

# ── CELL 8: PATCH CELL ────────────────────────────────────────────────────────
cells.append(md([
    "## Cell 8 — Patch Data Module for RFE2  ⚠️ MUST RUN EVERY SESSION\n",
    "\n",
    "Replaces three functions in the imported `data` module at runtime:\n",
    "\n",
    "| What gets patched | Original behaviour | New behaviour |\n",
    "|---|---|---|\n",
    "| `data.all_fcst_fields` | 14 IFS variables | 4 variables (tp, t2m, tcwv, sp) |\n",
    "| `data_module.load_truth_and_mask` | Loads IMERG 6h file | Loads RFE2 daily file, regrids to IFS |\n",
    "| `data.get_dates` | Checks IMERG file exists | Checks RFE2 file exists |\n",
    "| `DEFAULT_FCST_SHAPE` | (128,128,56) for 14 vars | (128,128,16) for 4 vars |\n",
    "\n",
    "**Why NOT divide by 4:** RFE2 mm/day is used as-is. `log10(1 + x)` handles the\n",
    "daily scale correctly. Dividing by 4 would assume uniform 6h distribution — physically wrong."
]))
cells.append(code([
    "import os, sys, numpy as np, xarray as xr\n",
    "from scipy.interpolate import RegularGridInterpolator\n",
    "from datetime import datetime, timedelta\n",
    "\n",
    "sys.path.insert(0, '/content/cGAN_tutorial')\n",
    "\n",
    "import data\n",
    "from data import data as data_module\n",
    "from config import get_data_paths\n",
    "\n",
    "# 1. Override forecast variable list\n",
    "data.all_fcst_fields = list(FORECAST_VARIABLES)\n",
    "\n",
    "# 2. IFS target grid constants\n",
    "IFS_LATS = np.arange(-13.65, 24.65 + 0.05, 0.1)   # 384 pts\n",
    "IFS_LONS = np.arange(19.15,  54.25 + 0.05, 0.1)   # 352 pts\n",
    "assert len(IFS_LATS) == 384, f'lat count {len(IFS_LATS)}'\n",
    "assert len(IFS_LONS) == 352, f'lon count {len(IFS_LONS)}'\n",
    "\n",
    "# 3. Get RFE2 path from config\n",
    "_data_paths = get_data_paths()\n",
    "_RFE_PATH   = _data_paths['GENERAL']['TRUTH_PATH'].rstrip('/')\n",
    "\n",
    "# 4. RFE2 truth loader\n",
    "def load_rfe2_truth(date_str, rfe_base_path=None):\n",
    "    path = rfe_base_path or _RFE_PATH\n",
    "    fpath = os.path.join(path, date_str[:4], f'{date_str}.nc')\n",
    "    ds   = xr.open_dataset(fpath)\n",
    "    rain = ds['precipitation'].values.copy()   # mm/day\n",
    "    lats = ds['lat'].values.copy()\n",
    "    lons = ds['lon'].values.copy()\n",
    "    ds.close()\n",
    "    # Flip to ascending latitude\n",
    "    if lats[0] > lats[-1]:\n",
    "        rain = rain[::-1, :]\n",
    "        lats = lats[::-1]\n",
    "    # Clean invalid values\n",
    "    rain = np.where(np.isnan(rain) | (rain < 0), 0.0, rain)\n",
    "    # Regrid to IFS 384x352\n",
    "    interp = RegularGridInterpolator(\n",
    "        (lats, lons), rain,\n",
    "        method='linear', bounds_error=False, fill_value=np.nan)\n",
    "    glon, glat = np.meshgrid(IFS_LONS, IFS_LATS)\n",
    "    rain_ifs   = interp((glat, glon))           # (384, 352)\n",
    "    mask       = np.isnan(rain_ifs)\n",
    "    rain_ifs   = np.where(mask, 0.0, rain_ifs)  # full daily mm/day, NOT /4\n",
    "    return rain_ifs.astype(np.float32), mask.astype(bool)\n",
    "\n",
    "# 5. Patched load_truth_and_mask\n",
    "def patched_load_truth_and_mask(date_str, hour, data_paths=None, log_precip=True):\n",
    "    rain, mask = load_rfe2_truth(date_str)\n",
    "    if log_precip:\n",
    "        rain = np.log10(1.0 + rain)\n",
    "    return rain[np.newaxis, :, :], mask[np.newaxis, :, :]\n",
    "\n",
    "data_module.load_truth_and_mask = patched_load_truth_and_mask\n",
    "\n",
    "# 6. Patched get_dates — checks RFE2 file, not IMERG\n",
    "def get_dates_rfe(year, start_hour=30, end_hour=54):\n",
    "    dates, cur = [], datetime(int(year), 1, 1)\n",
    "    while cur <= datetime(int(year), 12, 31):\n",
    "        d = cur.strftime('%Y%m%d')\n",
    "        if os.path.exists(os.path.join(_RFE_PATH, str(year), f'{d}.nc')):\n",
    "            dates.append(d)\n",
    "        cur += timedelta(days=1)\n",
    "    return dates\n",
    "\n",
    "data.get_dates = get_dates_rfe\n",
    "\n",
    "# 7. Fix DEFAULT_FCST_SHAPE for 4 variables\n",
    "from data import tfrecords_generator\n",
    "tfrecords_generator.DEFAULT_FCST_SHAPE = (128, 128, 4 * len(FORECAST_VARIABLES))\n",
    "\n",
    "print('Patches applied:')\n",
    "print(f'  all_fcst_fields     : {data.all_fcst_fields}')\n",
    "print(f'  load_truth_and_mask : {data_module.load_truth_and_mask.__name__}')\n",
    "print(f'  get_dates           : {data.get_dates.__name__}')\n",
    "print(f'  DEFAULT_FCST_SHAPE  : {tfrecords_generator.DEFAULT_FCST_SHAPE}')\n",
    "print(f'  _RFE_PATH           : {_RFE_PATH}')\n",
    "print(f'  RFE path exists     : {os.path.exists(_RFE_PATH)}')"
]))

# ── CELL 9: Diagnostics ───────────────────────────────────────────────────────
cells.append(md([
    "## Cell 9 — Diagnostics\n",
    "\n",
    "All 8 checks must show a tick before continuing.\n",
    "If any fail the cell prints the exact fix needed."
]))
cells.append(code([
    "print('=' * 60)\n",
    "print('DIAGNOSTIC CHECKS')\n",
    "print('=' * 60)\n",
    "\n",
    "results = {}\n",
    "\n",
    "# 1. get_dates patch\n",
    "fn = getattr(data.get_dates, '__name__', '')\n",
    "results[1] = ('get_dates patched', 'get_dates_rfe' in fn,\n",
    "              fn, 'Re-run Cell 8 (Patch Cell)')\n",
    "\n",
    "# 2. truth loader patch\n",
    "fn2 = getattr(data_module.load_truth_and_mask, '__name__', '')\n",
    "results[2] = ('truth loader patched', 'patched' in fn2,\n",
    "              fn2, 'Re-run Cell 8 (Patch Cell)')\n",
    "\n",
    "# 3. RFE path exists\n",
    "rfe_exists = os.path.exists(_RFE_PATH)\n",
    "results[3] = ('RFE base path exists', rfe_exists,\n",
    "              _RFE_PATH, 'Re-run Cell 1 to set RFE_DATA_DIR, then Cell 2 to unzip')\n",
    "\n",
    "# 4. At least one RFE year folder exists\n",
    "if rfe_exists:\n",
    "    rfe_dirs = [d for d in os.listdir(_RFE_PATH)\n",
    "                if os.path.isdir(os.path.join(_RFE_PATH, d)) and d.isdigit()]\n",
    "    rfe_dirs_ok = len(rfe_dirs) > 0\n",
    "    rfe_dirs_val = f'{sorted(rfe_dirs)} ({len(rfe_dirs)} years)'\n",
    "else:\n",
    "    rfe_dirs_ok, rfe_dirs_val = False, 'RFE path does not exist'\n",
    "results[4] = ('RFE year folders found', rfe_dirs_ok,\n",
    "              rfe_dirs_val,\n",
    "              'Re-run Cell 2. Check that zip files are uploaded to Drive at MyDrive/RFE_zips/YYYY.zip')\n",
    "\n",
    "# 5. Sample RFE2 file (use first available year)\n",
    "if rfe_exists and rfe_dirs_ok:\n",
    "    first_year = sorted(rfe_dirs)[0]\n",
    "    sample_files = os.listdir(os.path.join(_RFE_PATH, first_year))\n",
    "    sample_nc = sorted([f for f in sample_files if f.endswith('.nc')])\n",
    "    ok5 = len(sample_nc) > 0\n",
    "    sample_path = os.path.join(_RFE_PATH, first_year, sample_nc[0]) if ok5 else 'no .nc files found'\n",
    "else:\n",
    "    ok5, sample_path = False, 'no year folder found'\n",
    "results[5] = ('Sample RFE2 .nc file', ok5,\n",
    "              sample_path,\n",
    "              'Re-run Cell 2 with correct zip structure. Zip must contain YYYYMMDD.nc files.')\n",
    "\n",
    "# 6. FCSTNorm IFS exists\n",
    "norm_path = os.path.join(CONSTANTS_DIR, f'FCSTNorm{YEAR}.pkl')\n",
    "ok6 = os.path.exists(norm_path) and os.path.getsize(norm_path) > 1000\n",
    "results[6] = ('FCSTNorm (IFS) file', ok6,\n",
    "              norm_path, 'Re-run Cell 5 (download) then Cell 6 (copy)')\n",
    "\n",
    "# 7. IFS tp.nc exists\n",
    "ifs_tp = os.path.join(RAW_IFS_DIR, str(YEAR), 'tp.nc')\n",
    "ok7 = os.path.exists(ifs_tp) and os.path.getsize(ifs_tp) > 1e6\n",
    "results[7] = ('IFS tp.nc file', ok7,\n",
    "              ifs_tp, 'Re-run Cell 5 to re-download IFS forecast data')\n",
    "\n",
    "# 8. Date count for first available year\n",
    "if rfe_dirs_ok:\n",
    "    test_yr = int(sorted(rfe_dirs)[0])\n",
    "    date_count = len(data.get_dates(test_yr, START_HOUR, END_HOUR))\n",
    "    ok8 = date_count > 300\n",
    "    date_val = f'{date_count} dates for year {test_yr}'\n",
    "else:\n",
    "    ok8, date_val = False, 'no RFE year folders available'\n",
    "results[8] = ('Dates found via get_dates', ok8,\n",
    "              date_val, 'RFE2 files not found. Check Cell 2 output.')\n",
    "\n",
    "# Print results\n",
    "all_ok = True\n",
    "for num, (label, ok, value, fix) in results.items():\n",
    "    tick = 'OK' if ok else 'FAIL'\n",
    "    print(f'  [{tick}] {label}')\n",
    "    print(f'         value : {value}')\n",
    "    if not ok:\n",
    "        print(f'         fix   : {fix}')\n",
    "    all_ok = all_ok and ok\n",
    "\n",
    "print()\n",
    "if all_ok:\n",
    "    print('All checks passed. Safe to run Cell 10 and Cell 11.')\n",
    "else:\n",
    "    print('SOME CHECKS FAILED. Fix the issues above before proceeding.')\n",
    "    print('The most common causes:')\n",
    "    print('  - RFE2 zip not uploaded to Drive  -> upload YYYY.zip to MyDrive/RFE_zips/')\n",
    "    print('  - Cell 2 unzip did not run        -> re-run Cell 2')\n",
    "    print('  - IFS download failed             -> re-run Cell 5')\n",
    "    print('  - Patch cell not run              -> re-run Cell 8')"
]))

# ── CELL 10: Verify sample ────────────────────────────────────────────────────
cells.append(md([
    "## Cell 10 — Verify: Load One Sample and Plot\n",
    "\n",
    "**Important:** Uses `YEAR` (2018) as the test year because IFS forecast data on GCS\n",
    "is only available for 2018. RFE2 truth is read from the 2018 folder.\n",
    "If the IFS data hasn't been downloaded yet, Cell 5 must run first.\n",
    "\n",
    "Expected shapes:\n",
    "- `lo_res_inputs` : `(1, 384, 352, 16)` — IFS forecast\n",
    "- `hi_res_inputs` : `(1, 384, 352, 2)` — elevation + land-sea mask\n",
    "- `output`        : `(1, 384, 352, 1)` — RFE2 truth log-normalised\n",
    "- `mask`          : `(1, 384, 352, 1)` — validity mask"
]))
cells.append(code([
    "import matplotlib.pyplot as plt, pickle\n",
    "from data import DataGenerator, all_fcst_fields\n",
    "\n",
    "# Check Cell 5 ran first\n",
    "ifs_tp = os.path.join(RAW_IFS_DIR, str(YEAR), 'tp.nc')\n",
    "if not os.path.exists(ifs_tp):\n",
    "    raise FileNotFoundError(\n",
    "        f'IFS forecast file missing: {ifs_tp}\\n'\n",
    "        f'Run Cell 5 first to download IFS data from GCS.')\n",
    "\n",
    "# Load FCSTNorm into data module\n",
    "with open(os.path.join(CONSTANTS_DIR, f'FCSTNorm{YEAR}.pkl'), 'rb') as f:\n",
    "    fcst_norm_dict = pickle.load(f)\n",
    "data_module.fcst_norm = fcst_norm_dict\n",
    "print(f'FCSTNorm loaded: {len(fcst_norm_dict)} variables')\n",
    "\n",
    "# Use YEAR (2018) because IFS data is only available for that year on GCS\n",
    "# RFE2 truth for 2018 must also be present\n",
    "rfe_2018_dir = os.path.join(_RFE_PATH, str(YEAR))\n",
    "if not os.path.isdir(rfe_2018_dir) or len(os.listdir(rfe_2018_dir)) == 0:\n",
    "    raise RuntimeError(\n",
    "        f'RFE2 data for {YEAR} not found at {rfe_2018_dir}.\\n'\n",
    "        f'Run the repair cell and Cell 2 first.')\n",
    "\n",
    "test_year  = YEAR   # must match the year we have IFS data for\n",
    "test_dates = data.get_dates(test_year, START_HOUR, END_HOUR)\n",
    "print(f'Using year {test_year}: {len(test_dates)} dates available')\n",
    "\n",
    "if len(test_dates) == 0:\n",
    "    raise RuntimeError(f'No dates found for {test_year}. Check Cell 2 / repair cell output.')\n",
    "\n",
    "# Build DataGenerator with first 5 dates\n",
    "dgc = DataGenerator(\n",
    "    test_dates[:5],\n",
    "    fcst_fields=all_fcst_fields,\n",
    "    start_hour=START_HOUR,\n",
    "    end_hour=END_HOUR,\n",
    "    batch_size=1,\n",
    "    log_precip=True,\n",
    "    shuffle=False,\n",
    "    constants=True,\n",
    "    fcst_norm=True\n",
    ")\n",
    "\n",
    "sample = dgc.__getitem__(0)\n",
    "\n",
    "lo  = sample[0]['lo_res_inputs']\n",
    "hi  = sample[0]['hi_res_inputs']\n",
    "out = sample[1]['output']\n",
    "msk = sample[1]['mask']\n",
    "\n",
    "print(f'\\nShapes:')\n",
    "print(f'  lo_res_inputs : {lo.shape}   expected (1, 384, 352, 16)')\n",
    "print(f'  hi_res_inputs : {hi.shape}    expected (1, 384, 352, 2)')\n",
    "print(f'  output        : {out.shape}')\n",
    "print(f'  mask          : {msk.shape}')\n",
    "\n",
    "assert lo.shape  == (1, 384, 352, 16), f'Wrong lo_res shape: {lo.shape}'\n",
    "assert hi.shape  == (1, 384, 352, 2),  f'Wrong hi_res shape: {hi.shape}'\n",
    "print('Shape assertions passed.')\n",
    "\n",
    "# Extract output for plotting (handles both (1,384,352,1) and (1,384,352) shapes)\n",
    "truth_plot = out[0, :, :, 0] if out.ndim == 4 else out[0]\n",
    "\n",
    "print(f'  Truth value range : {truth_plot.min():.3f} to {truth_plot.max():.3f} (log-norm)')\n",
    "print(f'  Physical range    : {10**truth_plot.min()-1:.1f} to {10**truth_plot.max()-1:.1f} mm/day')\n",
    "print(f'  Masked pixels     : {msk.sum()} / {msk.size} ({100*msk.mean():.1f}% outside RFE2 domain)')\n",
    "\n",
    "# Plot\n",
    "fig, axes = plt.subplots(1, 3, figsize=(16, 5))\n",
    "\n",
    "im0 = axes[0].imshow(truth_plot, origin='lower', cmap='Blues', aspect='auto')\n",
    "plt.colorbar(im0, ax=axes[0])\n",
    "axes[0].set_title(f'RFE2 Truth (log-norm mm/day)\\n{test_dates[0]}')\n",
    "\n",
    "im1 = axes[1].imshow(lo[0, :, :, 0], origin='lower', cmap='Greens', aspect='auto')\n",
    "plt.colorbar(im1, ax=axes[1])\n",
    "axes[1].set_title('IFS tp input (channel 0, normalised)')\n",
    "\n",
    "mask_plot = msk[0, :, :, 0] if msk.ndim == 4 else msk[0]\n",
    "im2 = axes[2].imshow(mask_plot.astype(float), origin='lower', cmap='Reds', aspect='auto', vmin=0, vmax=1)\n",
    "plt.colorbar(im2, ax=axes[2])\n",
    "axes[2].set_title('Mask (red = outside RFE2 domain)')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.suptitle(f'Pipeline Verification — {test_dates[0]}', y=1.02, fontsize=12)\n",
    "plt.show()\n",
    "print('If left plot shows rainfall over East Africa: pipeline is correct.')"
]))

# ── CELL 11: TFRecord creation ────────────────────────────────────────────────
cells.append(md([
    "## Cell 11 — Create TFRecords\n",
    "\n",
    "Main loop. For each year:\n",
    "1. Gets all dates where RFE2 file exists\n",
    "2. Loads each day as a 384x352 image pair (IFS forecast + RFE2 truth)\n",
    "3. Extracts 8 random 128x128 patches per image\n",
    "4. Bins patches by mean rainfall intensity (4 classes)\n",
    "5. Writes GZIP-compressed TFRecord files to Drive\n",
    "\n",
    "**Rainfall bins (log-normalised, mm/day scale):**\n",
    "\n",
    "| Class | log-norm threshold | Physical approx | Weight |\n",
    "|---|---|---|---|\n",
    "| 0 dry | < 0.2 | < 6 mm/day | 40% |\n",
    "| 1 light | 0.2-0.3 | 6-9 mm/day | 30% |\n",
    "| 2 moderate | 0.3-0.45 | 9-18 mm/day | 20% |\n",
    "| 3 heavy | > 0.45 | > 18 mm/day | 10% |\n",
    "\n",
    "**Time:** ~5-10 min per year. Already-done years are skipped automatically.\n",
    "\n",
    "> Re-run Cell 8 first if this is a resumed session."
]))
cells.append(code([
    "import tensorflow as tf, random, time\n",
    "from tqdm import tqdm\n",
    "\n",
    "def _float_feature(value):\n",
    "    return tf.train.Feature(float_list=tf.train.FloatList(value=value.flatten()))\n",
    "\n",
    "IMG_H, IMG_W    = 384, 352\n",
    "PATCH_SIZE      = 128\n",
    "PATCHES_PER_IMG = 8\n",
    "NUM_CLASSES     = 4\n",
    "BIN_EDGES       = [0.2, 0.3, 0.45]   # log-normalised thresholds\n",
    "\n",
    "# Only process years where BOTH IFS and RFE2 data exist.\n",
    "# IFS data on GCS is only available for YEAR (2018).\n",
    "# Add more years here if you have your own IFS data for other years.\n",
    "ifs_years = sorted([\n",
    "    int(d) for d in os.listdir(RAW_IFS_DIR)\n",
    "    if os.path.isdir(os.path.join(RAW_IFS_DIR, d))\n",
    "    and os.path.exists(os.path.join(RAW_IFS_DIR, d, 'tp.nc'))])\n",
    "rfe_years = sorted([\n",
    "    int(d) for d in os.listdir(_RFE_PATH)\n",
    "    if os.path.isdir(os.path.join(_RFE_PATH, d)) and d.isdigit()\n",
    "    and len(os.listdir(os.path.join(_RFE_PATH, d))) > 0])\n",
    "process_years = sorted(set(ifs_years) & set(rfe_years))\n",
    "skip_years    = [y for y in ALL_YEARS if y not in process_years]\n",
    "\n",
    "print(f'IFS data years   : {ifs_years}')\n",
    "print(f'RFE2 data years  : {rfe_years[:5]}...  ({len(rfe_years)} total)')\n",
    "print(f'Years to process : {process_years}  (intersection — both IFS + RFE2 available)')\n",
    "if skip_years:\n",
    "    print(f'Years skipped    : {skip_years}  (no IFS data for these years)')\n",
    "    print('  To train on more years, download IFS data for those years')\n",
    "    print('  and add them to RAW_IFS_DIR using the same structure.')\n",
    "if not process_years:\n",
    "    raise RuntimeError(\n",
    "        'No processable years found. Run Cell 5 to download IFS data for 2018,'\n",
    "        ' then run the repair cell to fix RFE2 directory structure.')\n",
    "\n",
    "print(f'\\nStarting TFRecord creation...')\n",
    "if skip_years:\n",
    "    print(f'Years skipped    : {skip_years}  (no RFE2 data — upload zips and re-run Cell 2)')\n",
    "\n",
    "for year in process_years:\n",
    "    print(f'\\n{\"=\"*60}')\n",
    "    print(f'Year {year}')\n",
    "    print(f'{\"=\"*60}')\n",
    "\n",
    "    year_dates = data.get_dates(year, START_HOUR, END_HOUR)\n",
    "    print(f'  Dates available : {len(year_dates)}')\n",
    "\n",
    "    if len(year_dates) == 0:\n",
    "        print(f'  No dates — skipping.')\n",
    "        continue\n",
    "\n",
    "    # Skip years already done on Drive\n",
    "    existing = [f for f in os.listdir(OUTPUT_DIR)\n",
    "                if f.startswith(f'{year}_') and f.endswith('.tfrecords')]\n",
    "    if len(existing) >= NUM_CLASSES:\n",
    "        print(f'  Already done ({len(existing)} files on Drive). Skipping.')\n",
    "        continue\n",
    "\n",
    "    # DataGenerator for this year\n",
    "    dgc_year = DataGenerator(\n",
    "        year_dates,\n",
    "        fcst_fields=all_fcst_fields,\n",
    "        start_hour=START_HOUR,\n",
    "        end_hour=END_HOUR,\n",
    "        batch_size=1,\n",
    "        log_precip=True,\n",
    "        shuffle=False,\n",
    "        constants=True,\n",
    "        fcst_norm=True\n",
    "    )\n",
    "\n",
    "    # Open 4 TFRecord writers\n",
    "    opts    = tf.io.TFRecordOptions(compression_type='GZIP')\n",
    "    writers = [\n",
    "        tf.io.TFRecordWriter(\n",
    "            os.path.join(OUTPUT_DIR, f'{year}_30.{c}.tfrecords'), opts)\n",
    "        for c in range(NUM_CLASSES)]\n",
    "\n",
    "    written = [0] * NUM_CLASSES\n",
    "    t0 = time.time()\n",
    "\n",
    "    for idx in tqdm(range(len(year_dates)), desc=f'{year}'):\n",
    "        try:\n",
    "            sample = dgc_year.__getitem__(idx)\n",
    "        except Exception:\n",
    "            continue\n",
    "\n",
    "        for _ in range(PATCHES_PER_IMG):\n",
    "            ih = random.randint(0, IMG_H - PATCH_SIZE)\n",
    "            iw = random.randint(0, IMG_W - PATCH_SIZE)\n",
    "\n",
    "            # Skip patches outside RFE2 coverage\n",
    "            m = sample[1]['mask']\n",
    "            mc = m[0, ih:ih+PATCH_SIZE, iw:iw+PATCH_SIZE, 0] if m.ndim==4 else m[0, ih:ih+PATCH_SIZE, iw:iw+PATCH_SIZE]\n",
    "            if np.any(mc):\n",
    "                continue\n",
    "\n",
    "            o = sample[1]['output']\n",
    "            truth = o[0,ih:ih+PATCH_SIZE,iw:iw+PATCH_SIZE,0] if o.ndim==4 else o[0,ih:ih+PATCH_SIZE,iw:iw+PATCH_SIZE]\n",
    "            fcst  = sample[0]['lo_res_inputs'][0, ih:ih+PATCH_SIZE, iw:iw+PATCH_SIZE, :]\n",
    "            const = sample[0]['hi_res_inputs'][0, ih:ih+PATCH_SIZE, iw:iw+PATCH_SIZE, :]\n",
    "\n",
    "            mean_val = float(truth.mean())\n",
    "            clss = min(NUM_CLASSES-1, sum(1 for b in BIN_EDGES if mean_val >= b))\n",
    "\n",
    "            feat = {\n",
    "                'generator_input':  _float_feature(fcst),\n",
    "                'constants':        _float_feature(const),\n",
    "                'generator_output': _float_feature(truth),\n",
    "            }\n",
    "            writers[clss].write(\n",
    "                tf.train.Example(features=tf.train.Features(feature=feat)).SerializeToString())\n",
    "            written[clss] += 1\n",
    "\n",
    "    for w in writers:\n",
    "        w.close()\n",
    "\n",
    "    total = sum(written)\n",
    "    elapsed = time.time() - t0\n",
    "    if total > 0:\n",
    "        print(f'  Patches written : {written}  total={total}  time={elapsed/60:.1f}min')\n",
    "        print(f'  Distribution    : dry={written[0]/total*100:.0f}%  '\n",
    "              f'light={written[1]/total*100:.0f}%  '\n",
    "              f'mod={written[2]/total*100:.0f}%  '\n",
    "              f'heavy={written[3]/total*100:.0f}%')\n",
    "    else:\n",
    "        print(f'  WARNING: 0 patches written for {year}. Check mask coverage.')\n",
    "\n",
    "print(f'\\nDone. TFRecords at: {OUTPUT_DIR}')"
]))

# ── CELL 12: Summary ──────────────────────────────────────────────────────────
cells.append(md("## Cell 12 — Summary and Next Steps"))
cells.append(code([
    "tfr_files  = sorted(os.listdir(OUTPUT_DIR))\n",
    "years_done = sorted(set(f.split('_')[0] for f in tfr_files if f.endswith('.tfrecords')))\n",
    "total_mb   = sum(os.path.getsize(os.path.join(OUTPUT_DIR,f)) for f in tfr_files) / 1e6\n",
    "\n",
    "print('TFRecord Summary')\n",
    "print('='*50)\n",
    "print(f'Output dir    : {OUTPUT_DIR}')\n",
    "print(f'Total files   : {len(tfr_files)}')\n",
    "print(f'Years done    : {years_done}')\n",
    "print(f'Total size    : {total_mb:.0f} MB  ({total_mb/1024:.2f} GB)')\n",
    "\n",
    "missing = [str(y) for y in ALL_YEARS if str(y) not in years_done]\n",
    "if missing:\n",
    "    print(f'Years missing : {missing}')\n",
    "    print('  -> Upload their zips to Drive, re-run Cell 2, re-run Cell 11.')\n",
    "else:\n",
    "    print('All years processed.')\n",
    "\n",
    "print()\n",
    "train_done = [int(y) for y in years_done if int(y) < 2021]\n",
    "val_done   = [int(y) for y in years_done if int(y) >= 2021]\n",
    "print('Next: open Train_cGAN.ipynb and set:')\n",
    "print(f'  tfrecords_path = \"{OUTPUT_DIR}\"')\n",
    "print(f'  train_years    = {train_done}')\n",
    "print(f'  val_years      = {val_done}')"
]))

# ── Write notebook ─────────────────────────────────────────────────────────────
nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"},
        "colab": {"provenance": [], "gpuType": "T4"},
        "accelerator": "GPU"
    },
    "cells": cells
}

out = r'E:\CGAN\Retrain_cGAN\Create TFRecords.ipynb'
with open(out, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f'Written: {out}')
print(f'Cells  : {len(cells)}')
